// This file is auto-generated by scripts/build-registry.js
// Do not edit this file manually.

import React from 'react';
import { UiBox, UiFlexColumn, UiFlexRow, UiGrid, UiImage, UiLink, UiScrollBox, UiText } from './spm-components/primitives/LayoutPrimitives';
import { UiCommentListPage } from './spm-components/dedicated/UiCommentListPage';
import { UiDashboardPage } from './spm-components/dedicated/UiDashboardPage';
import { UiHeroLanding } from './spm-components/dedicated/UiHeroLanding';
import { UiImageCard } from './spm-components/dedicated/UiImageCard';
import { UiImageViewer } from './spm-components/dedicated/UiImageViewer';
import { UiModernGridPage } from './spm-components/dedicated/UiModernGridPage';
import { UiNavHeader } from './spm-components/dedicated/UiNavHeader';
import { UiPaginationBar } from './spm-components/dedicated/UiPaginationBar';
import { UiPostDetails } from './spm-components/dedicated/UiPostDetails';
import { UiScrollPanel } from './spm-components/dedicated/UiScrollPanel';
import { UiSearchBar } from './spm-components/dedicated/UiSearchBar';
import { UiSplitLayout } from './spm-components/dedicated/UiSplitLayout';
import { UiStatsDashboard } from './spm-components/dedicated/UiStatsDashboard';
import { UiTable } from './spm-components/dedicated/UiTable';
import { UiTableListPage } from './spm-components/dedicated/UiTableListPage';
import { UiTagBadge } from './spm-components/dedicated/UiTagBadge';
import { UiToast } from './spm-components/dedicated/UiToast';

export const COMPONENT_REGISTRY: Record<string, React.ComponentType<any>> = {
  UiBox,
  UiFlexColumn,
  UiFlexRow,
  UiGrid,
  UiImage,
  UiLink,
  UiScrollBox,
  UiText,
  UiCommentListPage,
  UiDashboardPage,
  UiHeroLanding,
  UiImageCard,
  UiImageViewer,
  UiModernGridPage,
  UiNavHeader,
  UiPaginationBar,
  UiPostDetails,
  UiScrollPanel,
  UiSearchBar,
  UiSplitLayout,
  UiStatsDashboard,
  UiTable,
  UiTableListPage,
  UiTagBadge,
  UiToast
};

export const PRIMITIVE_COMPONENTS = [
  'UiBox',
  'UiFlexColumn',
  'UiFlexRow',
  'UiGrid',
  'UiImage',
  'UiLink',
  'UiScrollBox',
  'UiText'
];

export const DEDICATED_COMPONENTS = [
  'UiCommentListPage',
  'UiDashboardPage',
  'UiHeroLanding',
  'UiImageCard',
  'UiImageViewer',
  'UiModernGridPage',
  'UiNavHeader',
  'UiPaginationBar',
  'UiPostDetails',
  'UiScrollPanel',
  'UiSearchBar',
  'UiSplitLayout',
  'UiStatsDashboard',
  'UiTable',
  'UiTableListPage',
  'UiTagBadge',
  'UiToast'
];
