name: Extension CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout extension repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Checkout spm-vscode intellisense repository
      uses: actions/checkout@v4
      with:
        repository: spm-ecosystem/spm-vscode
        path: ../vscode-theme-manifest-intellisense

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies in extension
      run: npm ci

    - name: Install dependencies in spm-vscode
      run: |
        cd ../vscode-theme-manifest-intellisense
        npm ci
        cd -

    - name: Run Build
      run: npm run build

    - name: Run Tests
      run: npm run test
