name: Extension Release CD

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout extension repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Checkout spm-vscode intellisense repository
      uses: actions/checkout@v4
      with:
        repository: spm-ecosystem/spm-vscode
        path: ../vscode-theme-manifest-intellisense

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies in extension
      run: npm ci

    - name: Install dependencies in spm-vscode
      run: |
        cd ../vscode-theme-manifest-intellisense
        npm ci
        cd -

    - name: Build Extension
      run: npm run build

    - name: Package extension to ZIP
      run: |
        cd dist
        zip -r ../release.zip .
        cd ..

    - name: Push to release-extension branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: release-extension
        target-folder: .
        clean: true
