name: Extension Release CD

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build Extension
      run: npm run build

    - name: Package extension to ZIP
      run: |
        cd dist
        zip -r ../release.zip .
        cd ..

    - name: Push to release-extension branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: release-extension
        target-folder: .
        clean: true
